### ISSUE TITLE
Android mobile app

### ISSUE THREAD

**Issue by Tibblez** [ZachJMoore/smart-kiln-hardware#12]
Is there any particular reason that this app is not available in Canada?  When I try to download it from the app store in my android device it says "This item is not available in your country".

The project doesn't seem to have a lot of activity recently that I can see.  Is it still active?  I just built a controller and am using jbruce12000's kiln controller codebase but the features are fairly limited.

**Comment by ZachJMoore** [comment]
Hey @Tibblez,

Thanks for your interest in the Smart Kiln. Unfortunately, I have not been in the ceramic industry for about the last two years now and have not had the time to continue updating the codebases. With that said, the servers are still running and it's possible to use the service, but service support will be very limited.

If you'd like to contribute to the code, you're more than welcome to, and would probably be the best option if you do want to use the service at this point.

In regard to the app, I will take a look and see about getting it available in your country!

**Comment by ZachJMoore** [comment]
The mobile app is now marked as available in Canada
